### ISSUE TITLE
API investigation 

### ISSUE THREAD

**Issue by kunal445** [Project4-Concert-Accountant/concert-accountant#2]
- [x] create an api feature branch
- [x] figure out the all the necessary api end points
- [x] create the api key
- [x] set up axios
- [x] useEffect hook 
- [x] make the api call
- [x] log the data

**Comment by JairoCalderon** [comment]
End points:
--events {
       --name
       --id
       --images
            --ratio
       --classification
            --segmentName
       --priceRange
            --currency
            --min
            --max
      --embedded
            --venues
